---
  version: '3.5'

  secrets:
    tomcat_ssl_crt:
      file: ./config/certificates/tomcat/tomcat-wildcard-dev.crt
    tomcat_ssl_key:
      file: ./config/certificates/tomcat/tomcat-wildcard-dev.key

  services:
    mlr-legacy:
      build: .
      image: mlr-legacy
      ports:
        - "8444:444"
      secrets:
        - source: tomcat_ssl_crt
          target: /tomcat-wildcard-ssl.crt
        - source: tomcat_ssl_key
          target: /tomcat-wildcard-ssl.key
      env_file:
        - config.env
        - secrets.env
